import { z } from 'zod';
export declare const WeaponSpecSchema: z.ZodObject<{
    id: z.ZodString;
    name: z.ZodString;
    damageType: z.ZodNativeEnum<any>;
    baseDamage: z.ZodNumber;
    range: z.ZodNumber;
    cooldownTicks: z.ZodNumber;
    splashRadius: z.ZodDefault<z.ZodNumber>;
    minRange: z.ZodDefault<z.ZodNumber>;
    projectileSpeed: z.ZodDefault<z.ZodNumber>;
    targetsAir: z.ZodDefault<z.ZodBoolean>;
    targetsGround: z.ZodDefault<z.ZodBoolean>;
    targetsNaval: z.ZodDefault<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    [x: string]: any;
    id?: unknown;
    name?: unknown;
    damageType?: unknown;
    baseDamage?: unknown;
    range?: unknown;
    cooldownTicks?: unknown;
    splashRadius?: unknown;
    minRange?: unknown;
    projectileSpeed?: unknown;
    targetsAir?: unknown;
    targetsGround?: unknown;
    targetsNaval?: unknown;
}, {
    [x: string]: any;
    id?: unknown;
    name?: unknown;
    damageType?: unknown;
    baseDamage?: unknown;
    range?: unknown;
    cooldownTicks?: unknown;
    splashRadius?: unknown;
    minRange?: unknown;
    projectileSpeed?: unknown;
    targetsAir?: unknown;
    targetsGround?: unknown;
    targetsNaval?: unknown;
}>;
export declare const UnitSpecSchema: z.ZodObject<{
    id: z.ZodString;
    legacyAlias: z.ZodOptional<z.ZodString>;
    name: z.ZodString;
    factionId: z.ZodNativeEnum<any>;
    category: z.ZodNativeEnum<any>;
    tier: z.ZodNativeEnum<any>;
    cost: z.ZodNumber;
    buildTimeSeconds: z.ZodNumber;
    commandCapCost: z.ZodNumber;
    hp: z.ZodNumber;
    shield: z.ZodDefault<z.ZodNumber>;
    armorType: z.ZodNativeEnum<any>;
    speed: z.ZodNumber;
    sightRange: z.ZodNumber;
    weaponId: z.ZodOptional<z.ZodString>;
    secondaryWeaponId: z.ZodOptional<z.ZodString>;
    abilities: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    prerequisites: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    passability: z.ZodDefault<z.ZodNativeEnum<any>>;
    harvesterCapacity: z.ZodOptional<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    [x: string]: any;
    id?: unknown;
    legacyAlias?: unknown;
    name?: unknown;
    factionId?: unknown;
    category?: unknown;
    tier?: unknown;
    cost?: unknown;
    buildTimeSeconds?: unknown;
    commandCapCost?: unknown;
    hp?: unknown;
    shield?: unknown;
    armorType?: unknown;
    speed?: unknown;
    sightRange?: unknown;
    weaponId?: unknown;
    secondaryWeaponId?: unknown;
    abilities?: unknown;
    prerequisites?: unknown;
    passability?: unknown;
    harvesterCapacity?: unknown;
}, {
    [x: string]: any;
    id?: unknown;
    legacyAlias?: unknown;
    name?: unknown;
    factionId?: unknown;
    category?: unknown;
    tier?: unknown;
    cost?: unknown;
    buildTimeSeconds?: unknown;
    commandCapCost?: unknown;
    hp?: unknown;
    shield?: unknown;
    armorType?: unknown;
    speed?: unknown;
    sightRange?: unknown;
    weaponId?: unknown;
    secondaryWeaponId?: unknown;
    abilities?: unknown;
    prerequisites?: unknown;
    passability?: unknown;
    harvesterCapacity?: unknown;
}>;
export declare const BuildingSpecSchema: z.ZodObject<{
    id: z.ZodString;
    legacyAlias: z.ZodOptional<z.ZodString>;
    name: z.ZodString;
    factionId: z.ZodNativeEnum<any>;
    category: z.ZodNativeEnum<any>;
    tier: z.ZodNativeEnum<any>;
    cost: z.ZodNumber;
    buildTimeSeconds: z.ZodNumber;
    commandCapGranted: z.ZodDefault<z.ZodNumber>;
    powerProduced: z.ZodDefault<z.ZodNumber>;
    powerConsumed: z.ZodDefault<z.ZodNumber>;
    hp: z.ZodNumber;
    shield: z.ZodDefault<z.ZodNumber>;
    armorType: z.ZodNativeEnum<any>;
    sightRange: z.ZodNumber;
    weaponId: z.ZodOptional<z.ZodString>;
    garrisonCapacity: z.ZodDefault<z.ZodNumber>;
    prerequisites: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    gridWidth: z.ZodDefault<z.ZodNumber>;
    gridHeight: z.ZodDefault<z.ZodNumber>;
    producesCategory: z.ZodOptional<z.ZodNativeEnum<any>>;
}, "strip", z.ZodTypeAny, {
    [x: string]: any;
    id?: unknown;
    legacyAlias?: unknown;
    name?: unknown;
    factionId?: unknown;
    category?: unknown;
    tier?: unknown;
    cost?: unknown;
    buildTimeSeconds?: unknown;
    commandCapGranted?: unknown;
    powerProduced?: unknown;
    powerConsumed?: unknown;
    hp?: unknown;
    shield?: unknown;
    armorType?: unknown;
    sightRange?: unknown;
    weaponId?: unknown;
    garrisonCapacity?: unknown;
    prerequisites?: unknown;
    gridWidth?: unknown;
    gridHeight?: unknown;
    producesCategory?: unknown;
}, {
    [x: string]: any;
    id?: unknown;
    legacyAlias?: unknown;
    name?: unknown;
    factionId?: unknown;
    category?: unknown;
    tier?: unknown;
    cost?: unknown;
    buildTimeSeconds?: unknown;
    commandCapGranted?: unknown;
    powerProduced?: unknown;
    powerConsumed?: unknown;
    hp?: unknown;
    shield?: unknown;
    armorType?: unknown;
    sightRange?: unknown;
    weaponId?: unknown;
    garrisonCapacity?: unknown;
    prerequisites?: unknown;
    gridWidth?: unknown;
    gridHeight?: unknown;
    producesCategory?: unknown;
}>;
export declare const FactionSpecSchema: z.ZodObject<{
    id: z.ZodNativeEnum<any>;
    name: z.ZodString;
    description: z.ZodString;
    resourceName: z.ZodString;
    resourceDescription: z.ZodString;
    hqBuildingId: z.ZodString;
    powerBuildingId: z.ZodString;
    refineryBuildingId: z.ZodString;
    barracksBuildingId: z.ZodString;
    factoryBuildingId: z.ZodString;
    techBuildingId: z.ZodString;
    defenseBuildingId: z.ZodString;
}, "strip", z.ZodTypeAny, {
    [x: string]: any;
    id?: unknown;
    name?: unknown;
    description?: unknown;
    resourceName?: unknown;
    resourceDescription?: unknown;
    hqBuildingId?: unknown;
    powerBuildingId?: unknown;
    refineryBuildingId?: unknown;
    barracksBuildingId?: unknown;
    factoryBuildingId?: unknown;
    techBuildingId?: unknown;
    defenseBuildingId?: unknown;
}, {
    [x: string]: any;
    id?: unknown;
    name?: unknown;
    description?: unknown;
    resourceName?: unknown;
    resourceDescription?: unknown;
    hqBuildingId?: unknown;
    powerBuildingId?: unknown;
    refineryBuildingId?: unknown;
    barracksBuildingId?: unknown;
    factoryBuildingId?: unknown;
    techBuildingId?: unknown;
    defenseBuildingId?: unknown;
}>;
export declare const ResourceNodeMapEntrySchema: z.ZodObject<{
    id: z.ZodString;
    x: z.ZodNumber;
    y: z.ZodNumber;
    isRich: z.ZodBoolean;
    creditsRemaining: z.ZodNumber;
}, "strip", z.ZodTypeAny, {
    id: string;
    x: number;
    y: number;
    isRich: boolean;
    creditsRemaining: number;
}, {
    id: string;
    x: number;
    y: number;
    isRich: boolean;
    creditsRemaining: number;
}>;
export declare const NeutralStructureMapEntrySchema: z.ZodObject<{
    id: z.ZodString;
    type: z.ZodEnum<["OIL_DERRICK", "REPAIR_DEPOT", "OBSERVATION_POST"]>;
    x: z.ZodNumber;
    y: z.ZodNumber;
}, "strip", z.ZodTypeAny, {
    id: string;
    type: "OIL_DERRICK" | "REPAIR_DEPOT" | "OBSERVATION_POST";
    x: number;
    y: number;
}, {
    id: string;
    type: "OIL_DERRICK" | "REPAIR_DEPOT" | "OBSERVATION_POST";
    x: number;
    y: number;
}>;
export declare const SpawnPointMapEntrySchema: z.ZodObject<{
    index: z.ZodNumber;
    x: z.ZodNumber;
    y: z.ZodNumber;
}, "strip", z.ZodTypeAny, {
    x: number;
    y: number;
    index: number;
}, {
    x: number;
    y: number;
    index: number;
}>;
export declare const MapDefinitionSchema: z.ZodObject<{
    id: z.ZodString;
    name: z.ZodString;
    width: z.ZodNumber;
    height: z.ZodNumber;
    maxPlayers: z.ZodNumber;
    spawnPoints: z.ZodArray<z.ZodObject<{
        index: z.ZodNumber;
        x: z.ZodNumber;
        y: z.ZodNumber;
    }, "strip", z.ZodTypeAny, {
        x: number;
        y: number;
        index: number;
    }, {
        x: number;
        y: number;
        index: number;
    }>, "many">;
    resourceNodes: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        x: z.ZodNumber;
        y: z.ZodNumber;
        isRich: z.ZodBoolean;
        creditsRemaining: z.ZodNumber;
    }, "strip", z.ZodTypeAny, {
        id: string;
        x: number;
        y: number;
        isRich: boolean;
        creditsRemaining: number;
    }, {
        id: string;
        x: number;
        y: number;
        isRich: boolean;
        creditsRemaining: number;
    }>, "many">;
    neutralStructures: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        type: z.ZodEnum<["OIL_DERRICK", "REPAIR_DEPOT", "OBSERVATION_POST"]>;
        x: z.ZodNumber;
        y: z.ZodNumber;
    }, "strip", z.ZodTypeAny, {
        id: string;
        type: "OIL_DERRICK" | "REPAIR_DEPOT" | "OBSERVATION_POST";
        x: number;
        y: number;
    }, {
        id: string;
        type: "OIL_DERRICK" | "REPAIR_DEPOT" | "OBSERVATION_POST";
        x: number;
        y: number;
    }>, "many">;
    heightMap: z.ZodArray<z.ZodArray<z.ZodNumber, "many">, "many">;
    passabilityGrid: z.ZodArray<z.ZodArray<z.ZodNumber, "many">, "many">;
}, "strip", z.ZodTypeAny, {
    width: number;
    height: number;
    id: string;
    name: string;
    maxPlayers: number;
    spawnPoints: {
        x: number;
        y: number;
        index: number;
    }[];
    resourceNodes: {
        id: string;
        x: number;
        y: number;
        isRich: boolean;
        creditsRemaining: number;
    }[];
    neutralStructures: {
        id: string;
        type: "OIL_DERRICK" | "REPAIR_DEPOT" | "OBSERVATION_POST";
        x: number;
        y: number;
    }[];
    heightMap: number[][];
    passabilityGrid: number[][];
}, {
    width: number;
    height: number;
    id: string;
    name: string;
    maxPlayers: number;
    spawnPoints: {
        x: number;
        y: number;
        index: number;
    }[];
    resourceNodes: {
        id: string;
        x: number;
        y: number;
        isRich: boolean;
        creditsRemaining: number;
    }[];
    neutralStructures: {
        id: string;
        type: "OIL_DERRICK" | "REPAIR_DEPOT" | "OBSERVATION_POST";
        x: number;
        y: number;
    }[];
    heightMap: number[][];
    passabilityGrid: number[][];
}>;
export declare const ContentDatabaseSchema: z.ZodObject<{
    factions: z.ZodArray<z.ZodObject<{
        id: z.ZodNativeEnum<any>;
        name: z.ZodString;
        description: z.ZodString;
        resourceName: z.ZodString;
        resourceDescription: z.ZodString;
        hqBuildingId: z.ZodString;
        powerBuildingId: z.ZodString;
        refineryBuildingId: z.ZodString;
        barracksBuildingId: z.ZodString;
        factoryBuildingId: z.ZodString;
        techBuildingId: z.ZodString;
        defenseBuildingId: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        [x: string]: any;
        id?: unknown;
        name?: unknown;
        description?: unknown;
        resourceName?: unknown;
        resourceDescription?: unknown;
        hqBuildingId?: unknown;
        powerBuildingId?: unknown;
        refineryBuildingId?: unknown;
        barracksBuildingId?: unknown;
        factoryBuildingId?: unknown;
        techBuildingId?: unknown;
        defenseBuildingId?: unknown;
    }, {
        [x: string]: any;
        id?: unknown;
        name?: unknown;
        description?: unknown;
        resourceName?: unknown;
        resourceDescription?: unknown;
        hqBuildingId?: unknown;
        powerBuildingId?: unknown;
        refineryBuildingId?: unknown;
        barracksBuildingId?: unknown;
        factoryBuildingId?: unknown;
        techBuildingId?: unknown;
        defenseBuildingId?: unknown;
    }>, "many">;
    buildings: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        legacyAlias: z.ZodOptional<z.ZodString>;
        name: z.ZodString;
        factionId: z.ZodNativeEnum<any>;
        category: z.ZodNativeEnum<any>;
        tier: z.ZodNativeEnum<any>;
        cost: z.ZodNumber;
        buildTimeSeconds: z.ZodNumber;
        commandCapGranted: z.ZodDefault<z.ZodNumber>;
        powerProduced: z.ZodDefault<z.ZodNumber>;
        powerConsumed: z.ZodDefault<z.ZodNumber>;
        hp: z.ZodNumber;
        shield: z.ZodDefault<z.ZodNumber>;
        armorType: z.ZodNativeEnum<any>;
        sightRange: z.ZodNumber;
        weaponId: z.ZodOptional<z.ZodString>;
        garrisonCapacity: z.ZodDefault<z.ZodNumber>;
        prerequisites: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        gridWidth: z.ZodDefault<z.ZodNumber>;
        gridHeight: z.ZodDefault<z.ZodNumber>;
        producesCategory: z.ZodOptional<z.ZodNativeEnum<any>>;
    }, "strip", z.ZodTypeAny, {
        [x: string]: any;
        id?: unknown;
        legacyAlias?: unknown;
        name?: unknown;
        factionId?: unknown;
        category?: unknown;
        tier?: unknown;
        cost?: unknown;
        buildTimeSeconds?: unknown;
        commandCapGranted?: unknown;
        powerProduced?: unknown;
        powerConsumed?: unknown;
        hp?: unknown;
        shield?: unknown;
        armorType?: unknown;
        sightRange?: unknown;
        weaponId?: unknown;
        garrisonCapacity?: unknown;
        prerequisites?: unknown;
        gridWidth?: unknown;
        gridHeight?: unknown;
        producesCategory?: unknown;
    }, {
        [x: string]: any;
        id?: unknown;
        legacyAlias?: unknown;
        name?: unknown;
        factionId?: unknown;
        category?: unknown;
        tier?: unknown;
        cost?: unknown;
        buildTimeSeconds?: unknown;
        commandCapGranted?: unknown;
        powerProduced?: unknown;
        powerConsumed?: unknown;
        hp?: unknown;
        shield?: unknown;
        armorType?: unknown;
        sightRange?: unknown;
        weaponId?: unknown;
        garrisonCapacity?: unknown;
        prerequisites?: unknown;
        gridWidth?: unknown;
        gridHeight?: unknown;
        producesCategory?: unknown;
    }>, "many">;
    units: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        legacyAlias: z.ZodOptional<z.ZodString>;
        name: z.ZodString;
        factionId: z.ZodNativeEnum<any>;
        category: z.ZodNativeEnum<any>;
        tier: z.ZodNativeEnum<any>;
        cost: z.ZodNumber;
        buildTimeSeconds: z.ZodNumber;
        commandCapCost: z.ZodNumber;
        hp: z.ZodNumber;
        shield: z.ZodDefault<z.ZodNumber>;
        armorType: z.ZodNativeEnum<any>;
        speed: z.ZodNumber;
        sightRange: z.ZodNumber;
        weaponId: z.ZodOptional<z.ZodString>;
        secondaryWeaponId: z.ZodOptional<z.ZodString>;
        abilities: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        prerequisites: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        passability: z.ZodDefault<z.ZodNativeEnum<any>>;
        harvesterCapacity: z.ZodOptional<z.ZodNumber>;
    }, "strip", z.ZodTypeAny, {
        [x: string]: any;
        id?: unknown;
        legacyAlias?: unknown;
        name?: unknown;
        factionId?: unknown;
        category?: unknown;
        tier?: unknown;
        cost?: unknown;
        buildTimeSeconds?: unknown;
        commandCapCost?: unknown;
        hp?: unknown;
        shield?: unknown;
        armorType?: unknown;
        speed?: unknown;
        sightRange?: unknown;
        weaponId?: unknown;
        secondaryWeaponId?: unknown;
        abilities?: unknown;
        prerequisites?: unknown;
        passability?: unknown;
        harvesterCapacity?: unknown;
    }, {
        [x: string]: any;
        id?: unknown;
        legacyAlias?: unknown;
        name?: unknown;
        factionId?: unknown;
        category?: unknown;
        tier?: unknown;
        cost?: unknown;
        buildTimeSeconds?: unknown;
        commandCapCost?: unknown;
        hp?: unknown;
        shield?: unknown;
        armorType?: unknown;
        speed?: unknown;
        sightRange?: unknown;
        weaponId?: unknown;
        secondaryWeaponId?: unknown;
        abilities?: unknown;
        prerequisites?: unknown;
        passability?: unknown;
        harvesterCapacity?: unknown;
    }>, "many">;
    weapons: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        name: z.ZodString;
        damageType: z.ZodNativeEnum<any>;
        baseDamage: z.ZodNumber;
        range: z.ZodNumber;
        cooldownTicks: z.ZodNumber;
        splashRadius: z.ZodDefault<z.ZodNumber>;
        minRange: z.ZodDefault<z.ZodNumber>;
        projectileSpeed: z.ZodDefault<z.ZodNumber>;
        targetsAir: z.ZodDefault<z.ZodBoolean>;
        targetsGround: z.ZodDefault<z.ZodBoolean>;
        targetsNaval: z.ZodDefault<z.ZodBoolean>;
    }, "strip", z.ZodTypeAny, {
        [x: string]: any;
        id?: unknown;
        name?: unknown;
        damageType?: unknown;
        baseDamage?: unknown;
        range?: unknown;
        cooldownTicks?: unknown;
        splashRadius?: unknown;
        minRange?: unknown;
        projectileSpeed?: unknown;
        targetsAir?: unknown;
        targetsGround?: unknown;
        targetsNaval?: unknown;
    }, {
        [x: string]: any;
        id?: unknown;
        name?: unknown;
        damageType?: unknown;
        baseDamage?: unknown;
        range?: unknown;
        cooldownTicks?: unknown;
        splashRadius?: unknown;
        minRange?: unknown;
        projectileSpeed?: unknown;
        targetsAir?: unknown;
        targetsGround?: unknown;
        targetsNaval?: unknown;
    }>, "many">;
    maps: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        name: z.ZodString;
        width: z.ZodNumber;
        height: z.ZodNumber;
        maxPlayers: z.ZodNumber;
        spawnPoints: z.ZodArray<z.ZodObject<{
            index: z.ZodNumber;
            x: z.ZodNumber;
            y: z.ZodNumber;
        }, "strip", z.ZodTypeAny, {
            x: number;
            y: number;
            index: number;
        }, {
            x: number;
            y: number;
            index: number;
        }>, "many">;
        resourceNodes: z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            x: z.ZodNumber;
            y: z.ZodNumber;
            isRich: z.ZodBoolean;
            creditsRemaining: z.ZodNumber;
        }, "strip", z.ZodTypeAny, {
            id: string;
            x: number;
            y: number;
            isRich: boolean;
            creditsRemaining: number;
        }, {
            id: string;
            x: number;
            y: number;
            isRich: boolean;
            creditsRemaining: number;
        }>, "many">;
        neutralStructures: z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            type: z.ZodEnum<["OIL_DERRICK", "REPAIR_DEPOT", "OBSERVATION_POST"]>;
            x: z.ZodNumber;
            y: z.ZodNumber;
        }, "strip", z.ZodTypeAny, {
            id: string;
            type: "OIL_DERRICK" | "REPAIR_DEPOT" | "OBSERVATION_POST";
            x: number;
            y: number;
        }, {
            id: string;
            type: "OIL_DERRICK" | "REPAIR_DEPOT" | "OBSERVATION_POST";
            x: number;
            y: number;
        }>, "many">;
        heightMap: z.ZodArray<z.ZodArray<z.ZodNumber, "many">, "many">;
        passabilityGrid: z.ZodArray<z.ZodArray<z.ZodNumber, "many">, "many">;
    }, "strip", z.ZodTypeAny, {
        width: number;
        height: number;
        id: string;
        name: string;
        maxPlayers: number;
        spawnPoints: {
            x: number;
            y: number;
            index: number;
        }[];
        resourceNodes: {
            id: string;
            x: number;
            y: number;
            isRich: boolean;
            creditsRemaining: number;
        }[];
        neutralStructures: {
            id: string;
            type: "OIL_DERRICK" | "REPAIR_DEPOT" | "OBSERVATION_POST";
            x: number;
            y: number;
        }[];
        heightMap: number[][];
        passabilityGrid: number[][];
    }, {
        width: number;
        height: number;
        id: string;
        name: string;
        maxPlayers: number;
        spawnPoints: {
            x: number;
            y: number;
            index: number;
        }[];
        resourceNodes: {
            id: string;
            x: number;
            y: number;
            isRich: boolean;
            creditsRemaining: number;
        }[];
        neutralStructures: {
            id: string;
            type: "OIL_DERRICK" | "REPAIR_DEPOT" | "OBSERVATION_POST";
            x: number;
            y: number;
        }[];
        heightMap: number[][];
        passabilityGrid: number[][];
    }>, "many">;
}, "strip", z.ZodTypeAny, {
    factions: {
        [x: string]: any;
        id?: unknown;
        name?: unknown;
        description?: unknown;
        resourceName?: unknown;
        resourceDescription?: unknown;
        hqBuildingId?: unknown;
        powerBuildingId?: unknown;
        refineryBuildingId?: unknown;
        barracksBuildingId?: unknown;
        factoryBuildingId?: unknown;
        techBuildingId?: unknown;
        defenseBuildingId?: unknown;
    }[];
    buildings: {
        [x: string]: any;
        id?: unknown;
        legacyAlias?: unknown;
        name?: unknown;
        factionId?: unknown;
        category?: unknown;
        tier?: unknown;
        cost?: unknown;
        buildTimeSeconds?: unknown;
        commandCapGranted?: unknown;
        powerProduced?: unknown;
        powerConsumed?: unknown;
        hp?: unknown;
        shield?: unknown;
        armorType?: unknown;
        sightRange?: unknown;
        weaponId?: unknown;
        garrisonCapacity?: unknown;
        prerequisites?: unknown;
        gridWidth?: unknown;
        gridHeight?: unknown;
        producesCategory?: unknown;
    }[];
    units: {
        [x: string]: any;
        id?: unknown;
        legacyAlias?: unknown;
        name?: unknown;
        factionId?: unknown;
        category?: unknown;
        tier?: unknown;
        cost?: unknown;
        buildTimeSeconds?: unknown;
        commandCapCost?: unknown;
        hp?: unknown;
        shield?: unknown;
        armorType?: unknown;
        speed?: unknown;
        sightRange?: unknown;
        weaponId?: unknown;
        secondaryWeaponId?: unknown;
        abilities?: unknown;
        prerequisites?: unknown;
        passability?: unknown;
        harvesterCapacity?: unknown;
    }[];
    weapons: {
        [x: string]: any;
        id?: unknown;
        name?: unknown;
        damageType?: unknown;
        baseDamage?: unknown;
        range?: unknown;
        cooldownTicks?: unknown;
        splashRadius?: unknown;
        minRange?: unknown;
        projectileSpeed?: unknown;
        targetsAir?: unknown;
        targetsGround?: unknown;
        targetsNaval?: unknown;
    }[];
    maps: {
        width: number;
        height: number;
        id: string;
        name: string;
        maxPlayers: number;
        spawnPoints: {
            x: number;
            y: number;
            index: number;
        }[];
        resourceNodes: {
            id: string;
            x: number;
            y: number;
            isRich: boolean;
            creditsRemaining: number;
        }[];
        neutralStructures: {
            id: string;
            type: "OIL_DERRICK" | "REPAIR_DEPOT" | "OBSERVATION_POST";
            x: number;
            y: number;
        }[];
        heightMap: number[][];
        passabilityGrid: number[][];
    }[];
}, {
    factions: {
        [x: string]: any;
        id?: unknown;
        name?: unknown;
        description?: unknown;
        resourceName?: unknown;
        resourceDescription?: unknown;
        hqBuildingId?: unknown;
        powerBuildingId?: unknown;
        refineryBuildingId?: unknown;
        barracksBuildingId?: unknown;
        factoryBuildingId?: unknown;
        techBuildingId?: unknown;
        defenseBuildingId?: unknown;
    }[];
    buildings: {
        [x: string]: any;
        id?: unknown;
        legacyAlias?: unknown;
        name?: unknown;
        factionId?: unknown;
        category?: unknown;
        tier?: unknown;
        cost?: unknown;
        buildTimeSeconds?: unknown;
        commandCapGranted?: unknown;
        powerProduced?: unknown;
        powerConsumed?: unknown;
        hp?: unknown;
        shield?: unknown;
        armorType?: unknown;
        sightRange?: unknown;
        weaponId?: unknown;
        garrisonCapacity?: unknown;
        prerequisites?: unknown;
        gridWidth?: unknown;
        gridHeight?: unknown;
        producesCategory?: unknown;
    }[];
    units: {
        [x: string]: any;
        id?: unknown;
        legacyAlias?: unknown;
        name?: unknown;
        factionId?: unknown;
        category?: unknown;
        tier?: unknown;
        cost?: unknown;
        buildTimeSeconds?: unknown;
        commandCapCost?: unknown;
        hp?: unknown;
        shield?: unknown;
        armorType?: unknown;
        speed?: unknown;
        sightRange?: unknown;
        weaponId?: unknown;
        secondaryWeaponId?: unknown;
        abilities?: unknown;
        prerequisites?: unknown;
        passability?: unknown;
        harvesterCapacity?: unknown;
    }[];
    weapons: {
        [x: string]: any;
        id?: unknown;
        name?: unknown;
        damageType?: unknown;
        baseDamage?: unknown;
        range?: unknown;
        cooldownTicks?: unknown;
        splashRadius?: unknown;
        minRange?: unknown;
        projectileSpeed?: unknown;
        targetsAir?: unknown;
        targetsGround?: unknown;
        targetsNaval?: unknown;
    }[];
    maps: {
        width: number;
        height: number;
        id: string;
        name: string;
        maxPlayers: number;
        spawnPoints: {
            x: number;
            y: number;
            index: number;
        }[];
        resourceNodes: {
            id: string;
            x: number;
            y: number;
            isRich: boolean;
            creditsRemaining: number;
        }[];
        neutralStructures: {
            id: string;
            type: "OIL_DERRICK" | "REPAIR_DEPOT" | "OBSERVATION_POST";
            x: number;
            y: number;
        }[];
        heightMap: number[][];
        passabilityGrid: number[][];
    }[];
}>;
export type ContentDatabase = z.infer<typeof ContentDatabaseSchema>;
//# sourceMappingURL=index.d.ts.map